media:
  - name: articles_images
    label: Articles Media
    input: src/data/articles
    output: src/data/articles

  - name: resources_images
    label: Resources Media
    input: src/data/resources
    output: src/data/resources

  - name: about_images
    label: About Media
    input: src/data/about/images
    output: src/data/about/images

content:
  - name: articles
    label: Articles
    type: collection
    path: src/data/articles
    format: yaml-frontmatter
    filename: index.mdx # saves each post in a folder with index.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: author
        label: Author
        type: string
      - name: isFeatured
        label: Featured Article
        type: boolean
        default: false
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
      - name: image
        label: Image Filepath
        type: string
        default: ./images/{replace-with-the-real-image-filename.ext}
        type: string
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: articleSection
        label: Article Section (Optional)
        type: string
        required: false
        description: "e.g., California Labor Law, Hiring & Compliance"
      - name: keywords
        label: Keywords (Optional)
        type: string
        list: true
        required: false
        description: "SEO keywords and topics (e.g., SB 1162, pay transparency)"
      - name: youtubeUrl
        label: YouTube Video URL
        type: string
        required: false
        description: "Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=xxxxx)"
      - name: hasVideoSchema
        label: Add Video to Google Search
        type: boolean
        default: false
        required: false
        description: "Check this if the video should appear in Google Video search results"
      - name: videoTitle
        label: Video Title (Optional)
        type: string
        required: false
        description: "Leave blank to use article title"
      - name: videoDescription
        label: Video Description (Optional)
        type: text
        required: false
        description: "Leave blank to use article excerpt"
      - name: videoUploadDate
        label: Video Upload Date (Optional)
        type: date
        required: false
        description: "Set the actual YouTube video upload date. Leave blank to use article date"
      - name: videoDuration
        label: Video Duration (Optional)
        type: string
        required: false
        description: "ISO 8601 format (e.g., PT5M30S for 5 minutes 30 seconds)"
      - name: videoViewCount
        label: Video View Count (Optional)
        type: number
        required: false
        description: "Approximate view count for Google rich results"
      - name: videoRegionsAllowed
        label: Video Regions Allowed (Optional)
        type: string
        list: true
        required: false
        description: "Region codes where video is allowed (e.g., US, CA, MX)"
      - name: faqs
        label: FAQs (Optional)
        type: object
        list: true
        required: false
        fields:
          - name: question
            label: Question
            type: string
            required: true
          - name: answer
            label: Answer
            type: text
            required: true
      - name: body
        label: Body
        type: code
        options:
          language: html

  # Resources Collection
  - name: resources
    label: Resources
    type: collection
    path: src/data/resources
    format: yaml-frontmatter
    filename: index.mdx # saves each post in a folder with index.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: provider
        label: Provider
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: category
        label: Category
        type: string
        required: true
      - name: priceRange
        label: Price Range
        type: string
        required: true
      - name: rating
        label: Rating
        type: number
        required: false
      - name: isFeatured
        label: Featured Resources
        type: boolean
        default: false
        required: true
      - name: image
        label: Image Filepath
        type: string
        default: ./images/{replace-with-the-real-image-filename.ext}
        type: string
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: code
        options:
          language: html

  # Privacy Policy Collection
  - name: policies
    label: Privacy Policies
    type: collection
    path: src/data/privacy
    format: yaml-frontmatter
    filename: privacy.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: lastUpdated
        label: Last Updated
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text

  # Accessibility Statement Collection
  - name: accessible
    label: ADA Statements
    type: collection
    path: src/data/accessibility
    format: yaml-frontmatter
    filename: accessibility.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: lastUpdated
        label: Last Updated
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text

  # About Page Collection
  - name: about
    label: About Page
    type: file
    path: src/data/about/about.mdx
    format: yaml-frontmatter
    fields:
      - name: title
        label: Page Title (SEO)
        type: string
        required: true
      - name: pageTitle
        label: Page Title (Display)
        type: string
        required: true
      - name: description
        label: Meta Description
        type: text
        required: true
      - name: heading
        label: Main Heading
        type: string
        required: true
      - name: intro
        label: Introduction Text
        type: text
        required: true
      - name: tagline
        label: Tagline
        type: string
        required: true
      - name: image
        label: Profile Image
        type: string
        default: ./images/hr-personel.png
        required: true
      - name: imageAlt
        label: Image Alt Text
        type: string
        required: true
      - name: ctaHeading
        label: CTA Heading
        type: string
        required: true
      - name: ctaButtonText
        label: CTA Button Text
        type: string
        required: true
      - name: ctaButtonLink
        label: CTA Button Link
        type: string
        required: false

settings:
  content:
    merge: true
