media:
  - name: blog_images
    label: Blog Media
    input: src/data/blogs
    output: src/data/blogs
    categories: [image]
    extensions: [svg, png, jpg, jpeg, webp]

content:
  - name: blogs
    label: Blogs
    type: collection
    path: src/data/blogs
    format: yaml-frontmatter
    filename: index.mdx # saves each post in a folder with index.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: author
        label: Author
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
      - name: image
        label: Cover Image
        type: image
        required: true
        options:
          media: blog_images
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text

settings:
  content:
    merge: true
