media:
  - name: articles_images
    label: Articles Media
    input: src/data/articles
    output: src/data/articles

  - name: resources_images
    label: Resources Media
    input: src/data/resources
    output: src/data/resources

content:
  - name: articles
    label: Articles
    type: collection
    path: src/data/articles
    format: yaml-frontmatter
    filename: index.mdx # saves each post in a folder with index.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: author
        label: Author
        type: string
      - name: isFeatured
        label: Featured Article
        type: boolean
        default: false
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
      - name: image
        label: Image Filepath
        type: string
        default: ./images/{replace-with-the-real-image-filename.ext}
        type: string
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: youtubeUrl
        label: YouTube Video URL
        type: string
        required: false
        description: "Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=xxxxx)"
      - name: hasVideoSchema
        label: Add Video to Google Search
        type: boolean
        default: false
        required: false
        description: "Check this if the video should appear in Google Video search results"
      - name: videoTitle
        label: Video Title (Optional)
        type: string
        required: false
        description: "Leave blank to use article title"
      - name: videoDescription
        label: Video Description (Optional)
        type: text
        required: false
        description: "Leave blank to use article excerpt"
      - name: body
        label: Body
        type: code
        options:
          language: html

  # Resources Collection
  - name: resources
    label: Resources
    type: collection
    path: src/data/resources
    format: yaml-frontmatter
    filename: index.mdx # saves each post in a folder with index.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: provider
        label: Provider
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: category
        label: Category
        type: string
        required: true
      - name: priceRange
        label: Price Range
        type: string
        required: true
      - name: rating
        label: Rating
        type: number
        required: false
      - name: isFeatured
        label: Featured Resources
        type: boolean
        default: false
        required: true
      - name: image
        label: Image Filepath
        type: string
        default: ./images/{replace-with-the-real-image-filename.ext}
        type: string
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: code
        options:
          language: html

  # Privacy Policy Collection
  - name: policies
    label: Privacy Policies
    type: collection
    path: src/data/privacy
    format: yaml-frontmatter
    filename: privacy.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: lastUpdated
        label: Last Updated
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text

  # Accessibility Statement Collection
  - name: accessible
    label: ADA Statements
    type: collection
    path: src/data/accessibility
    format: yaml-frontmatter
    filename: accessibility.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: lastUpdated
        label: Last Updated
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text

settings:
  content:
    merge: true
